name: Build-Test CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: cache-venv
      env:
        cache-name: env-cached-v1
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ env.cache-name }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-${{ env.cache-name }}-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m venv ./.venv && . ./.venv/bin/activate && pip install -r requirements.txt
      if: ${{ steps.cache-venv.outputs.cache-hit != 'true' }}
    - name: Run Tests
      run: |
        . ./.venv/bin/activate && make githubworkflow
